USER_PROFILE_PICTURE_MAX_SIZE_BYTES = 1024 * 1024
USER_PROFILE_PICTURE_MAX_SIZE_HUMAN_READABLE = "1MB"
USER_PROFILE_PICTURE_ACCEPTED_MIME_TYPES = {
    "png": "image/png",
    "jpg": "image/jpg",
    "jpeg": "image/jpeg",
}
